# Generated by Django 2.1.3 on 2018-11-17 19:40

import ckeditor_uploader.fields
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('slug', models.SlugField(unique=True, verbose_name='id_url')),
                ('upload_date', models.DateTimeField(default=datetime.datetime.now)),
                ('description', models.CharField(max_length=500)),
                ('article', ckeditor_uploader.fields.RichTextUploadingField()),
                ('image', models.ImageField(upload_to='photos/blog_post/%Y/%m/%d/')),
                ('image_alt', models.CharField(max_length=300)),
            ],
        ),
    ]
